/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Layout & Grid
    'grid-cols-7',
    'min-w-[1024px]',
    'max-w-[1600px]',
    'max-w-7xl',
    'max-w-5xl',
    'max-w-4xl',
    'overflow-x-auto',
    'overflow-y-auto',
    'inline-block',
    'align-top',
    
    // Text Alignment & Typography
    'text-center',
    'text-left',
    'text-right',
    'text-3xl',
    'text-2xl',
    'text-xl',
    'text-lg',
    'text-sm',
    'text-xs',
    'font-bold',
    'font-semibold',
    'font-medium',
    'truncate',
    'leading-tight',
    'leading-relaxed',
    
    // Flexbox & Alignment
    'flex',
    'flex-1',
    'flex-wrap',
    'items-center',
    'items-start',
    'items-end',
    'justify-between',
    'justify-center',
    'justify-end',
    'gap-2',
    'gap-3',
    'gap-4',
    'space-x-2',
    'space-x-4',
    'space-y-6',
    
    // Spacing & Sizing
    'p-2',
    'p-4',
    'p-6',
    'p-8',
    'px-2',
    'px-3',
    'px-4',
    'px-6',
    'py-1',
    'py-2',
    'py-3',
    'py-4',
    'py-8',
    'w-full',
    'w-4',
    'w-5',
    'w-8',
    'w-10',
    'w-20',
    'w-24',
    'w-32',
    'h-4',
    'h-5',
    'h-8',
    'max-h-[400px]',
    'min-h-screen',
    
    // Borders & Backgrounds
    'border',
    'border-b',
    'border-t',
    'border-gray-200',
    'border-gray-300',
    'rounded',
    'rounded-lg',
    'rounded-xl',
    'rounded-full',
    'divide-y',
    'divide-gray-200',
    'bg-white',
    'bg-gray-50',
    'bg-gray-100',
    'bg-blue-600',
    'bg-green-600',
    'bg-red-600',
    'bg-gray-400',
    'bg-gray-800',
    'bg-gray-900',
    'hover:bg-gray-50',
    'hover:bg-blue-700',
    'hover:bg-green-700',
    'hover:bg-red-700',
    'hover:bg-gray-500',
    'shadow',
    'shadow-sm',
    'shadow-lg',
    
    // Forms & Interactive
    'form-checkbox',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:ring-blue-500',
    'focus:border-blue-500',
    'hover:text-blue-800',
    'hover:text-red-800',
    'hover:text-green-800',
    'text-blue-600',
    'text-red-600',
    'text-green-600',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-800',
    'text-white',
    'cursor-pointer',
    'cursor-not-allowed',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    
    // Table Utilities
    'table-auto',
    'border-collapse',
    
    // Transitions & Animations
    'transition-all',
    'transition-colors',
    'duration-150',
    'duration-200',
    'animate-spin',
    'transform',
    'hover:scale-[1.02]',
    
    // Margins & Position
    'mb-4',
    'mb-6',
    'mb-8',
    'mt-4',
    'mt-6',
    'mx-auto',
    'sticky',
    'top-0',
    'z-10',
    'z-50'
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)'
      },
      fontFamily: {
        sans: ['Inter', 'Segoe UI', 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
      },
      spacing: {
        '18': '4.5rem',
        '112': '28rem',
        '128': '32rem',
      },
      minHeight: {
        '112': '28rem',
        '128': '32rem',
      },
      maxWidth: {
        '8xl': '88rem',
        '9xl': '96rem',
      },
      screens: {
        '3xl': '1920px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
